// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Password    string    `gorm:"column:password;not null" json:"password"`
	Dob         time.Time `gorm:"column:dob" json:"dob"`
	Pob         string    `gorm:"column:pob" json:"pob"`
	PhoneNumber string    `gorm:"column:phoneNumber" json:"phoneNumber"`
	Address     string    `gorm:"column:address" json:"address"`
	IsActive    int32     `gorm:"column:isActive;not null" json:"isActive"`
	Otp         string    `gorm:"column:otp" json:"otp"`
	CreateAt    string    `gorm:"column:createAt;not null" json:"createAt"`
	UpdateAt    string    `gorm:"column:updateAt" json:"updateAt"`
	DeleteAt    string    `gorm:"column:deleteAt" json:"deleteAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
